FROM bitnamilegacy/kafka:latest

ENV KAFKA_HEAP_OPTS="-Xmx256m -Xms256m"

# Enable KRaft mode (no Zookeeper needed)
ENV KAFKA_ENABLE_KRAFT=yes
ENV KAFKA_CFG_NODE_ID=0
ENV KAFKA_CFG_PROCESS_ROLES=controller,broker
ENV KAFKA_CFG_LISTENERS=PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
ENV KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
ENV KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@localhost:9093
ENV KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
ENV ALLOW_PLAINTEXT_LISTENER=yes
